# Generated by Django 6.0.6 on 2026-06-29 21:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_terminal', models.CharField(blank=True, default='', max_length=8)),
                ('terminal', models.CharField(max_length=8)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('opening_float', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_terminal', models.CharField(blank=True, default='', max_length=8)),
                ('terminal', models.CharField(max_length=8)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('number', models.CharField(blank=True, default='', max_length=32)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('timbre_amount_snapshot', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('refund_method', models.CharField(default='CASH', max_length=8)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_terminal', models.CharField(blank=True, default='', max_length=8)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('ret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.return')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_terminal', models.CharField(blank=True, default='', max_length=8)),
                ('terminal', models.CharField(max_length=8)),
                ('customer_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('FINALIZED', 'FINALIZED'), ('VOIDED', 'VOIDED'), ('REFUNDED', 'REFUNDED')], default='DRAFT', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('timbre_amount_snapshot', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('currency', models.CharField(default='TND', max_length=3)),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.cashsession')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='return',
            name='original_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='sales.sale'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_terminal', models.CharField(blank=True, default='', max_length=8)),
                ('method', models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD'), ('ACCOUNT', 'ACCOUNT'), ('VOUCHER', 'VOUCHER')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('tpe_ref', models.CharField(blank=True, default='', max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_terminal', models.CharField(blank=True, default='', max_length=8)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
