# Generated by Django 6.0.6 on 2026-06-29 21:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalStampConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=12, unique=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(max_length=8)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('doc_type', models.CharField(max_length=12)),
                ('seq', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('terminal', 'year', 'month', 'doc_type')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('FACTURE', 'FACTURE'), ('TICKET', 'TICKET'), ('AVOIR', 'AVOIR')], default='FACTURE', max_length=12)),
                ('terminal', models.CharField(max_length=8)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('seq', models.IntegerField()),
                ('fiscal_number', models.CharField(max_length=32, unique=True)),
                ('timbre_amount_snapshot', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('immutable', models.BooleanField(default=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='sales.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
