# Generated by Django 6.0.6 on 2026-06-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='store_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
