# Generated by Django 6.0.6 on 2026-06-29 21:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_terminal', models.CharField(blank=True, default='', max_length=8)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.CharField(choices=[('RECEIPT', 'RECEIPT'), ('SALE', 'SALE'), ('RETURN', 'RETURN'), ('ADJUST', 'ADJUST'), ('TRANSFER', 'TRANSFER'), ('STOCKTAKE', 'STOCKTAKE')], max_length=12)),
                ('unit_cost', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('ref_type', models.CharField(blank=True, default='', max_length=24)),
                ('ref_id', models.CharField(blank=True, default='', max_length=64)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'created_at'], name='inventory_s_product_5919a9_idx')],
            },
        ),
    ]
