# Generated by Django 6.0.6 on 2026-06-29 21:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_terminal', models.CharField(blank=True, default='', max_length=8)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('matricule_fiscal', models.CharField(blank=True, default='', max_length=32)),
                ('credit_limit', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_terminal', models.CharField(blank=True, default='', max_length=8)),
                ('entry_type', models.CharField(choices=[('CHARGE', 'CHARGE'), ('PAYMENT', 'PAYMENT')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14)),
                ('ref_type', models.CharField(blank=True, default='', max_length=24)),
                ('ref_id', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='customers.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'created_at'], name='customers_a_custome_05961e_idx')],
            },
        ),
    ]
