# Generated by Django 6.0.6 on 2026-06-30 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('ASSET', 'ASSET'), ('LIABILITY', 'LIABILITY'), ('EQUITY', 'EQUITY'), ('REVENUE', 'REVENUE'), ('EXPENSE', 'EXPENSE')], max_length=10)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('memo', models.CharField(blank=True, default='', max_length=200)),
                ('ref_type', models.CharField(blank=True, default='', max_length=24)),
                ('ref_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ref_type', 'ref_id'], name='ledger_jour_ref_typ_6699a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ledger.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.journalentry')),
            ],
        ),
    ]
