# Generated by Django 6.0.6 on 2026-07-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationline',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
