# Generated by Django 6.0.6 on 2026-06-29 21:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_terminal', models.CharField(blank=True, default='', max_length=8)),
                ('name', models.CharField(max_length=32)),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_terminal', models.CharField(blank=True, default='', max_length=8)),
                ('name_fr', models.CharField(max_length=128)),
                ('name_ar', models.CharField(blank=True, default='', max_length=128)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_terminal', models.CharField(blank=True, default='', max_length=8)),
                ('sku', models.CharField(max_length=48, unique=True)),
                ('internal_code', models.CharField(blank=True, default='', max_length=48)),
                ('name_fr', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, default='', max_length=200)),
                ('cost_avg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('sale_price', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('qty_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('reorder_point', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('reorder_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('is_book', models.BooleanField(default=False)),
                ('isbn', models.CharField(blank=True, default='', max_length=13)),
                ('allow_negative', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.taxrate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_terminal', models.CharField(blank=True, default='', max_length=8)),
                ('value', models.CharField(db_index=True, max_length=64)),
                ('symbology', models.CharField(default='EAN13', max_length=16)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='catalog.product')),
            ],
            options={
                'unique_together': {('value', 'symbology')},
            },
        ),
    ]
