# Generated by Django 6.0.6 on 2026-06-30 04:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_terminal', models.CharField(blank=True, default='', max_length=8)),
                ('name', models.CharField(max_length=160, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_terminal', models.CharField(blank=True, default='', max_length=8)),
                ('isbn13', models.CharField(blank=True, db_index=True, default='', max_length=13)),
                ('isbn10', models.CharField(blank=True, default='', max_length=10)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('publisher', models.CharField(blank=True, default='', max_length=160)),
                ('series', models.CharField(blank=True, default='', max_length=160)),
                ('edition', models.CharField(blank=True, default='', max_length=80)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('pub_year', models.IntegerField(blank=True, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('dimensions', models.CharField(blank=True, default='', max_length=60)),
                ('cover_type', models.CharField(blank=True, default='', max_length=40)),
                ('subject', models.CharField(blank=True, default='', max_length=160)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('source_provider', models.CharField(blank=True, default='', max_length=40)),
                ('ocr_confidence', models.FloatField(default=0.0)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_terminal', models.CharField(blank=True, default='', max_length=8)),
                ('image', models.ImageField(upload_to='product_images/%Y/%m/')),
                ('kind', models.CharField(choices=[('COVER', 'COVER'), ('BACK', 'BACK'), ('PAGE', 'PAGE'), ('OTHER', 'OTHER')], default='COVER', max_length=8)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookContributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_terminal', models.CharField(blank=True, default='', max_length=8)),
                ('role', models.CharField(choices=[('AUTHOR', 'AUTHOR'), ('TRANSLATOR', 'TRANSLATOR'), ('EDITOR', 'EDITOR'), ('ILLUSTRATOR', 'ILLUSTRATOR')], default='AUTHOR', max_length=12)),
                ('order', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='catalog.book')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.contributor')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('book', 'contributor', 'role')},
            },
        ),
    ]
