# Generated by Django 6.0.6 on 2026-06-30 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contributor_book_productimage_bookcontributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], default='PENDING', max_length=8)),
                ('isbn', models.CharField(blank=True, default='', max_length=20)),
                ('image_ids', models.JSONField(default=list)),
                ('result', models.JSONField(blank=True, null=True)),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
