# Generated by Django 6.0.6 on 2026-07-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_scanjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty_on_hand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_qty',
            field=models.IntegerField(default=0),
        ),
    ]
