# Generated by Django 6.0.6 on 2026-06-29 21:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.BooleanField(default=True, unique=True)),
                ('last_pull_cursor', models.CharField(blank=True, default='', max_length=64)),
                ('last_push_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('op', models.CharField(default='UPSERT', max_length=8)),
                ('payload', models.TextField(default='[]')),
                ('origin_terminal', models.CharField(default='', max_length=8)),
                ('seq', models.BigIntegerField()),
                ('pushed', models.BooleanField(default=False)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['pushed', 'seq'], name='sync_syncou_pushed_671436_idx')],
            },
        ),
    ]
