# Generated by Django 6.0.6 on 2026-07-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='qty_ordered',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='qty_received',
            field=models.IntegerField(default=0),
        ),
    ]
